### ISSUE TITLE
libFirm panic in assure_should_be_same_requirements: Unresolved should_be_same constraint

### ISSUE THREAD

**Issue by rofl0r** [libfirm/cparser#4]
when you delete the src/complex directory from musl libc [1], it can be built without complex math support. this is the next issue i run into:

/media/3T/git-mirror/musl[complex-less]$ make
/media/3T/git-mirror/cparser/build/debug/cparser -m32 -std=c99 -nostdinc -ffreestanding  -D_XOPEN_SOURCE=700 -I./arch/i386 -I./src/internal -I./include  -Os -pipe -fomit-frame-pointer -fno-asynchronous-unwind-tables -Wa,--noexecstack  -c -o src/exit/exit.o src/exit/exit.c
warning: ignoring unknown option -Wa,--noexecstack
./include/stdio.h:150:7: warning: redundant declaration for 'function ctermid' (declared at line 121:7 of "./include/unistd.h") [-Wredundant-decls]
1 warning(s)
be_Keep ANY[2695:286] not scheduled after its pred node in block Block BB[858:1](exit)
ir/be/ia32/ia32_finish.c:334: libFirm panic in assure_should_be_same_requirements: Unresolved should_be_same constraint
make: **\* [src/exit/exit.o] Aborted
make: **\* Deleting file `src/exit/exit.o'

[1] http://www.musl-libc.org

**Comment by UniQP** [comment]
This is already fixed (probably in f179d707807854554ec6cb150ae8e64f0603ee87).
